#!/u/dontignx/IFT3225-TP1/venv/bin/python3
from bs4 import BeautifulSoup
import requests
import argparse

def main():
    # Intitialize argument parser
    parser = argparse.ArgumentParser(
        prog='extract', 
        description="Extrait les ressources image et vidéo d'une page HTML",
        usage = "/.extract [-r <regex>] [-i] [-v] [-p <path>] [-h] <url>"
        )

    # Add arguments
    parser.add_argument('url', help='URL de la page HTML')
    parser.add_argument('-r', '--regex', help='Liste seulement les ressources dont le nom match l\'expression régulière')
    parser.add_argument('-i', '--images', help='Ne liste pas les éléments <img> (default: liste)', action='store_false')
    parser.add_argument('-v', '--videos', help='Ne liste pas les éléments <video> (default: liste)', action='store_false')
    parser.add_argument('-p', '--path', help='Liste et copie les ressources img et/ou video de <url> dans le path (default: juste liste)')

    # Parse arguments
    args = parser.parse_args()

    # Get the page content into a beautiful soup object
    page = requests.get(args.url)
    soup = BeautifulSoup(page.content, "html.parser")

    # Print path
    if args.path:
        print('PATH', args.path)
    else:
        print('PATH', args.url)

    # Extract images and videos
    for tag in soup.find_all(["img", "video"]):
        # Reset resource info
        type = None
        src = None
        alt = None

        # Get resource info
        if tag.name == 'img' and args.images:
            type = 'IMAGE'
            src = tag.get('src')
            alt = tag.get('alt')
        elif tag.name == 'video' and args.videos:
            type = 'VIDEO'
            if tag.get('src'):
                src = tag.get('src')
            else:
                src = tag.source.get('src')

        # Output resource info
        regex = args.regex if args.regex else ''
        
        if regex in src: # Check if the resource name matches the regex
            if type == 'IMAGE':
                if alt:
                    print('IMAGE', src, alt)
                else:
                    print('IMAGE', src)
            elif type == 'VIDEO':
                print('VIDEO', src)

if __name__ == '__main__':
    main()