#!/usr/bin/env python3
import argparse

def main():
    parser = argparse.ArgumentParser(
        prog='extract', 
        description="Extrait les ressources image et vidéo d'une page HTML",
        usage = "/.extract [-r <regex>] [-i] [-v] [-p <path>] [-h] <url>"
        )

    parser.add_argument('url', help='URL de la page HTML')
    parser.add_argument('-r', '--regex', help='Regex pour filtrer les URLs')
    parser.add_argument('-i', '--images', help='Extrait les images', action='store_true')
    parser.add_argument('-v', '--videos', help='Extrait les vidéos', action='store_true')
    parser.add_argument('-p', '--path', help='Chemin de destination')

    args = parser.parse_args()

    print(args)

if __name__ == '__main__':
    main()