#!/www/ens/hiver/dontignx/public_html/IFT3225-TP1/venv/bin/python3
import sys

def main():
    base_path = ""
    resources = []

    for line in sys.stdin:
        line = line.strip()
        if line.startswith('PATH'):
            base_path = line.split(' ')[1]
        elif line.startswith('IMAGE'):
            parts = line.split(' ', 2)
            url = parts[1]
            if len(parts) > 2:
                alt = parts[2]
            else:
                alt = ''
            resources.append((url, alt, 'IMAGE'))
        elif line.startswith('VIDEO'):
            resources.append((line.split(' ')[1], '', 'VIDEO'))

    print("<!DOCTYPE html>")
    print("<html lang=\"en\">")
    print("<head>")
    print("    <meta charset=\"UTF-8\">")
    print("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">")
    print("    <title>Document</title>")
    print("    <link rel=\"stylesheet\" href=\"style.css\">")
    print("    <link href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" rel=\"stylesheet\">")
    print("</head>")
    print("<body>")
    print("")
    print("    <div class=\"container\" id=\"container\">")
    print("        <div class=\"container text-center\">")
    print("            <h1>Visualisateur</h1>")
    print("            <p>d'images/vidéo</p>")
    print("        </div>")
    print("")
    print("        <table id=\"table\" class=\"table\">")
    print("            <tr class=\"table-light\">")
    print("                <th>ressource</th>")
    print("                <th>alt</th>")
    print("            </tr>")
    for url, alt, res_type in resources:
        new_url = base_path + '/' + url
        class_name = "image" if res_type == "IMAGE" else "video"
        print(f"        <tr class=\"{class_name}\">")
        print(f"            <td>{new_url}</td>")
        print(f"            <td>{alt}</td>")
        print("        </tr>")
    print("    </table>")
    print("")
    print("    <div class=\"container text-center\" id=\"image-container\"></div>")
    print("")
    print("    <div class=\"hstack text-center\" id=\"buttons\">")
    print("        <button id=\"carrousel\" class=\"btn btn-primary\">Carrousel</button>")
    print("        <button id=\"gallerie\" class=\"btn btn-primary\">Gallerie</button>")
    print("    </div>")
    print("")
    print("</body>")
    print("<script src=\"script.js\"></script>")
    print("</html>")

if __name__ == '__main__':
    try:
        main()
    except BrokenPipeError:
        pass